### ISSUE TITLE
fails to build with aeson-2.0

### ISSUE THREAD

**Issue by juhp** [pbrisbin/bugsnag-haskell#69]
```
bugsnag-haskell           > /tmp/stack-152970be5185369b/bugsnag-haskell-0.0.4.1/src/Network/Bugsnag/BugsnagRequestHeaders.hs:29:5: error:
bugsnag-haskell           >     • Couldn't match expected type ‘Key’
bugsnag-haskell           >                   with actual type ‘Data.Text.Internal.Text’
bugsnag-haskell           >     • In the first argument of ‘(.=)’, namely
bugsnag-haskell           >         ‘TE.decodeUtf8 (CI.original name)’
bugsnag-haskell           >       In the expression:
bugsnag-haskell           >         TE.decodeUtf8 (CI.original name) .= String (TE.decodeUtf8 value)
bugsnag-haskell           >       In an equation for ‘headerToKeyValue’:
bugsnag-haskell           >           headerToKeyValue (name, value)
bugsnag-haskell           >             = TE.decodeUtf8 (CI.original name) .= String (TE.decodeUtf8 value)
bugsnag-haskell           >    |
bugsnag-haskell           > 29 |     TE.decodeUtf8 (CI.original name) .= String (TE.decodeUtf8 value)
bugsnag-haskell           >    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by pbrisbin** [comment]
Should be fixed in 0.0.4.2.
